name: koreapostredesign
description: Korea Post Redesign Project

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_slider: ^2.0.0
  flutter_vector_icons: ^0.2.1
  sliding_up_panel: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: NanumGothic
      fonts:
        - asset: fonts/NanumGothicCoding-Regular.ttf
